# Generated by Django 4.1.7 on 2023-07-19 11:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(default='abc@email.com', max_length=180, primary_key=True, serialize=False)),
                ('resy_email', models.CharField(default='abc@email.com', max_length=180)),
                ('resy_pwd', models.CharField(default='abc', max_length=180)),
                ('user_name', models.CharField(default='abc', max_length=180)),
                ('user_token', models.TextField(default='abc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=180)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(blank=True, default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.TextField(default='abc')),
                ('rest_name', models.CharField(max_length=180)),
                ('rest_id', models.IntegerField()),
                ('date', models.DateField()),
                ('from_time', models.TimeField(default=datetime.time(8, 0))),
                ('to_time', models.TimeField(default=datetime.time(8, 0))),
                ('number_of_guests', models.IntegerField()),
                ('booking_available_till', models.DateField()),
                ('is_booking_date_active', models.BooleanField(default=False)),
                ('booking_confirm', models.CharField(default='Pending', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.ForeignKey(default='abc@email.com', on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_status', models.CharField(default='Pending', max_length=100)),
                ('reservation_id', models.TextField(default='abc')),
                ('reservation_cnf_token', models.TextField(default='abc')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.reservation_request')),
            ],
        ),
    ]
