# Generated by Django 4.1.7 on 2023-07-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_restaurant_user_resy_reservation_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation_request',
            name='user_email',
        ),
    ]
