# Generated by Django 4.1.7 on 2023-07-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_reservation_request_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation_request',
            name='booking_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
